### ISSUE TITLE
Create way for users to sync to local calendar

### ISSUE THREAD

**Issue by jonathanlo411** [ucsdds3/ds3-site#215]
Some user calendars can be the one used on Windows, Mac, etc. In addition it should be viable to sync into a Google Calendar.

Note:
- Users should ideally not need to download a `.ics` file.
- Should be integrated seamlessly within current design. May need to contact design to get some wireframes.
- Users should be able to sync either the entire calendar or just an event.

**Comment by CodingKomodo** [comment]
For clarification, do you want the users to be able to sync their details into the DS3 calendar or do you want them to sync the DS3 calendar into their local calendars.

**Comment by jonathanlo411** [comment]
I would like them to sync the DS3 calendar to their local calendars. Since we are constantly updating the calendar as new events come up, I would prefer that they would not need need to constantly go back to the DS3 UCSD website and instead have it become a checkbox format like the following:
![image](https://github.com/ucsdds3/ds3-site/assets/72477459/2731bec1-3b1d-452c-a1fc-e8a57abf1f86)
