### ISSUE TITLE
Make the Board page Mobile-Friendly

### ISSUE THREAD

**Issue by CodingKomodo** [ucsdds3/ds3-site#267]
To make the Board Page mobile friendly, we need to use media queries to change the layout of the cards. We need to make the layout of the grid of board members into a column so instead of rows of 4, there should be a single column where each card has its own row. In order to do this, you will need to utilize media queries and css in both the page.svelte for the board and the boardcard.svelte. This issue is similar to #266 and read that issue to get a better understanding of what I am looking for. Here is a [video](https://www.youtube.com/watch?v=ZYV6dYtz4HA) for reference.

**Comment by Anshu-b** [comment]
Submitted, please let me know for changes.
